---
title: "Maeotias"
author: "Caroline Newell"
date: "1/26/2022"
output: word_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(lfstat)

MaeotiasQuery2022 <- read_excel("data/MaeotiasEffortQuery.xlsx")
range(MaeotiasQuery2022$SampleDate)

drought_years<-c(1976, 1977, 1987, 1988, 1989, 1990, 1991, 1992, 2007, 2008, 2009, 2012, 2013, 2014, 2015, 2016, 2020, 2021) #data from: https://water.ca.gov/water-basics/drought  and Peter (2020, 2021)
```

# Parsing Flows
Only care about outflow since that is what impacts the jellies.
```{r}
DeltaFlow_WY.1981_2021<- DeltaFlow_WaterYears1960_2021 %>% 
  filter(Date >="1980-10-01") %>% 
  mutate(WaterYear = water_year(Date, origin = "usgs")) %>% 
  group_by(WaterYear) %>% 
  summarise(Outflow_MAF = sum(OUT*1.983)/1000000) #24 hours at 1 cfs  = 1.983 acre feet
str(DeltaFlow_WY.1981_2021) #Need water year to be viewed as an integer.

DeltaFlow_WY.1981_2021$WaterYear<-format(DeltaFlow_WY.1981_2021$WaterYear, format = "%Y")

DeltaFlow_WY.1981_2021$WaterYear<-lubridate::year(DeltaFlow_WY.1981_2021$WaterYear)
  
  #year(as.Date(as.character(DeltaFlow_WY.1981_2021$WaterYear), format="%Y")) #Recognizing year as number I guess.
```

# Wrangling Maeotias Data
Need to give data water year information.

```{r}
#Adding water year to jelly data
MaeotiasQuery2022<-MaeotiasQuery2022 %>% mutate(WaterYear = water_year(SampleDate, origin = "usgs"))

str(MaeotiasQuery2022)

#Appending flow info to jelly data
#Actually I don't need to do that for this presentation...
#Maeotias2022<-full_join(MaeotiasQuery2022, DeltaFlow_WY.1981_2021, by="WaterYear") #Lovely! Write that up!

#write.csv(Maeotias2022, "data/Maeotias2022_WithOutflow.csv")


```

#Total Catch of M Marginata

```{r}
str(MaeotiasQuery2022)
MaeotiasQuery2022$WaterYear<-format(MaeotiasQuery2022$WaterYear, format = "%Y")

MaeotiasQuery2022$WaterYear<- as.Date(as.character(MaeotiasQuery2022$WaterYear), format = "%Y")

MaeotiasQuery2022$WaterYear<- lubridate::year(MaeotiasQuery2022$WaterYear)

MaeotiasQuery2022$Month<- format(MaeotiasQuery2022$SampleDate, format = "%m")
MaeotiasQuery2022_WaterYearNumeric<- MaeotiasQuery2022
write.csv(MaeotiasQuery2022_WaterYearNumeric, "data/MaeotiasQuery2022_WaterYearNumeric.csv")
```

## Plotting
```{r}

ggplot(data = MaeotiasQuery2022_WaterYearNumeric, aes(x=WaterYear, y = Count)) +  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  stat_summary(fun=sum, geom = "bar")+ xlab("Water Year") +  ylab("Count") + ggtitle("SMFS Total Catch of M. marginata")+ scale_x_continuous(breaks=c(1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 

ggplot(data = MaeotiasQuery2022_WaterYearNumeric, aes(x=Month, y = Count)) +
  stat_summary(fun=sum, geom = "bar")

ggplot(data = MaeotiasQuery2022_WaterYearNumeric, aes(x=StationCode, y = Count)) +
  stat_summary(fun=sum, geom = "bar")
```

#Catch per unit effort

```{r}
str(MaeotiasQuery2022_WaterYearNumeric)
#A plot of effort but only for the trawls that caught maeotias.
ggplot(data = MaeotiasQuery2022_WaterYearNumeric, aes(x=WaterYear, y = Count/TowDuration)) +  geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  stat_summary(fun=sum, geom = "bar")+ xlab("Water Year") +  ylab("Catch per Minute Trawl") + ggtitle("SMFS CPUE of M. marginata \nfor Trawls that Caught M. marginata")+ scale_x_continuous(breaks=c(1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 
#This plot shows how spotty they are. When you catch 'em, you catch a lot.

#Now I want a true reflection of CPUE that includes trawls that didn't catch Mm
```

#CPUE All Trawls

```{r}
Trawls <- read_excel("data/Trawls.xlsx")

Trawls_WY<-Trawls %>% mutate(WaterYear = water_year(SampleDate, origin = "usgs"))
unique(Trawls_WY$WaterYear)
#Give trawls water years
Trawls_WY_Sum<- Trawls_WY %>% group_by(WaterYear) %>% summarise(
  TrawlDurationSum = sum(na.omit(TowDuration))
)
#Sweet
write.csv(Trawls_WY_Sum, "data/Trawls_WY_Sum.csv")

#Now I want to sum the catch of Mm by year in a dataframe.
MaeotiasQuery2022_WaterYearSum<-MaeotiasQuery2022_WaterYearNumeric %>% group_by(WaterYear) %>% summarise(
  CountSum=sum(Count)
)

#Now we merge
MaeotiasCPUE_AllTrawls<- merge(MaeotiasQuery2022_WaterYearSum, Trawls_WY_Sum, by = "WaterYear")

#Add a column of CPUE
MaeotiasCPUE_AllTrawls<- mutate(MaeotiasCPUE_AllTrawls, CPUE = CountSum/TrawlDurationSum)
#I will think about deleting 2022. May be construed as misleading.
```

Cool, I can plot now.

## Plotting

###Year
```{r}
ggplot(MaeotiasCPUE_AllTrawls, aes(x=WaterYear, y=CPUE))+ geom_rect(aes(xmin=1987, xmax=1992, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2007, xmax=2009, ymin=0, ymax=Inf),fill = "grey75", alpha = .1) +
  geom_rect(aes(xmin=2012, xmax=2016, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  geom_rect(aes(xmin=2020, xmax=2021, ymin=0, ymax=Inf),fill = "grey75", alpha = .1)+
  stat_summary(fun=sum, geom = "bar")+ xlab("Water Year") +  ylab("Catch per Minute Trawl") + ggtitle("SMFS CPUE of M. marginata \nfor All Trawls")+ scale_x_continuous(breaks=c(1980, 1990, 2000, 2010, 2020))+
  theme_classic(base_size=16) 
```

###Month
```{r}
Trawls<- Trawls %>% mutate(Month=month(SampleDate))

Trawl_Month<- Trawls %>% group_by(Month) %>% summarise(TrawlDurationSum = sum(na.omit(TowDuration)))

MaeotiasQuery2022_Month<-MaeotiasQuery2022_WaterYearNumeric %>% group_by(Month) %>% summarise(CountSum = sum(Count))
view(MaeotiasQuery2022_Month)

str(MaeotiasQuery2022_Month)
str(Trawl_Month)

MaeotiasQuery2022_Month$Month<- as.numeric(MaeotiasQuery2022_Month$Month)

Maeotias_AllTrawls_ByMonth<- merge(MaeotiasQuery2022_Month, Trawl_Month, by = "Month")
view(Maeotias_AllTrawls_ByMonth)

MaeotiasCPUE_AllTrawls_ByMonth<- mutate(MaeotiasCPUE_AllTrawls_ByMonth, Month_CPUE = na.omit(CountSum/TrawlDurationSum))

view(MaeotiasCPUE_AllTrawls_ByMonth)

ggplot(data = MaeotiasCPUE_AllTrawls_ByMonth, aes(x=Month, y = Month_CPUE)) +
  stat_summary(fun=sum, geom = "bar")+
  theme_classic(base_size=16) + scale_x_continuous(breaks=c(01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12)) + ggtitle("SMFS CPUE of M. marginata by Month \nfor All Trawls")
```

### Site
```{r}
ggplot(data = MaeotiasQuery2022_WaterYearNumeric, aes(x=StationCode, y = Count)) +
  stat_summary(fun=sum, geom = "bar")
```